# Define la sección de configuración de pytest.
[pytest]

# Agrega el directorio raíz del proyecto al PYTHONPATH para
# permitir importar módulos y paquetes del proyecto.
pythonpath = .

# Indica que pytest debe buscar los archivos de prueba dentro
# de la carpeta "tests"
testpaths = tests

# Define el patrón de nombres que deben tener los archivos de prueba.
# En este caso, deben comenzar con "test_" y tener extensión ".py".
python_files = test_*.py

# Desactiva el plugin de caché de pytest para evitar que se genere
# la carpeta ".pytest_cache" al ejecutar las pruebas.
addopts = -p no:cacheprovider

markers =
    ui: Pruebas de interfaz de usuario